### ISSUE TITLE
Changing the tour state with a driver results in an error-page

### ISSUE THREAD

**Issue by Dasteme** [scg-unibe-ch/ese2017-team7#14]
Changing the tour state with a driver results in an error-page

**Steps to reproduce the bug**
Create a tour with an admin
Assign a driver to the tour
Log in as Driver
Click "Change Status"
Change the status from "undelivered" to "delivered"
Click "Submit"

**Expected Behavior**
It should show tours instead of an error-page

**The reason behind the bug and location of the bug**
change-status-success.html  has a missing  '  on line 17 after ROLE_USER

**Comment by axyndus** [comment]
Fixed, thanks.
