### ISSUE TITLE
It's not possible to set a password with special characters

### ISSUE THREAD

**Issue by Dasteme** [scg-unibe-ch/ese2017-team7#15]
It's not possible to set a password with special characters

**Steps to reproduce the bug**
Go to "Account", "Register"
Enter a name and an Email
Enter a password like  Test12$

**Expected and observed behavior**
Expected:  A new account
Observed: A message which says "The password has to contain a regular letter,
                 a capital letter and a number"

**The reason behind the bug**
In User.java, on line 28 the regex doesn't allow special characters

**Comment by axyndus** [comment]
Fixed to allow the following characters: _@$!%*?&£öäüéàè\-
