### ISSUE TITLE
Creating two accounts with the same eMail results in an error-page

### ISSUE THREAD

**Issue by Dasteme** [scg-unibe-ch/ese2017-team7#16]
Creating two accounts with the same eMail results in an error-page

**Steps to reproduce the bug**
Create an account
Create a second account with the same eMail

**Expected and observed behavior**
Expected: A new account or a warning message which says that the eMail is already assigned
Observed: An error-page

**The reason behind the bug**
No check if the eMail is already assigned

**Comment by axyndus** [comment]
this is no longer possible.
